apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-opening-deployment
  labels:
    app: account-opening
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-account-opening
  template:
    metadata:
      labels:
        app: demo-account-opening
    spec:
      containers:
        - name: demo-account-opening
          image: demo-account-opening:20250101001
          ports:
            - containerPort: 4000
          resources:
            limits:
              memory: "1024Mi"
              cpu: "1000m"
            requests:
              memory: "1024Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: demo-account-opening-service
spec:
  type: NodePort
  selector:
    app: demo-account-opening
  ports:
    - port: 4000
      protocol: TCP
      targetPort: 4000
      nodePort: 30003
