apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-master-data-service
  labels:
    app: demo-master-data-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-master-data-service
  template:
    metadata:
      labels:
        app: demo-master-data-service
    spec:
      containers:
        - image: myominhtoo/demo-master-data-service:20250101001
          name: demo-master-data-service
          ports:
            - containerPort: 3000
          resources:
            limits:
              memory: "1024Mi"
              cpu: "1000m"
            requests:
              memory: "1024Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: demo-master-data-service
spec:
  selector:
    app: demo-master-data-service
  type: NodePort
  ports:
    - port: 8000
      protocol: TCP
      targetPort: 3000
      nodePort: 30002
