apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-react-app
  labels:
    app: demo-react-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-react-app
  template:
    metadata:
      labels:
        app: demo-react-app
    spec:
      containers:
        - image: myominhtoo/demo-react-app:20250101001
          name: demo-react-app
          ports:
            - containerPort: 3000
          resources:
            limits:
              memory: "1024Mi"
              cpu: "1000m"
            requests:
              memory: "1024Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: demo-react-app-service
spec:
  selector:
    app: demo-react-app
  type: NodePort
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
      nodePort: 30001
